{{- if .Values.fileImport.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "wordpress.fullname" . }}-files-import
  labels:
    {{- include "wordpress.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "-4"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      restartPolicy: Never
      containers:
        - name: files-import
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          securityContext:
            allowPrivilegeEscalation: true
            privileged: true
          command:
            - /bin/sh
            - -c
            - |
              set -e
              curl -sSL {{ .Values.minioClientDownload }} -o /tmp/mc
              chmod +x /tmp/mc
              /tmp/mc alias set s3 $S3_URL $S3_ACCESS_KEY $S3_SECRET_KEY
              echo "Syncing files for WordPress..."
              /tmp/mc ls s3
              /tmp/mc ls s3/{{ .Values.fileImport.bucket }}
              /tmp/mc cp --recursive s3/{{ .Values.fileImport.bucket }} {{ .Values.fileImport.path }}
          env:
            - name: S3_URL
              valueFrom:
                secretKeyRef:
                  name: s3-storage
                  key: S3_URL
            - name: S3_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: s3-storage
                  key: S3_ACCESS_KEY
            - name: S3_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: s3-storage
                  key: S3_SECRET_KEY
          volumeMounts:
            - name: data
              mountPath: /var/www/html/web/app/mirror
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: {{ include "wordpress.fullname" . }}-data
{{- end }}